name: build-and-push-to-dh
on: workflow_dispatch
# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '17 18 * * *'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - uses: docker/login-action@v2
        with:
            username: ${{ secrets.DH_USERNAME }}
            password: ${{ secrets.DH_TOKEN }}
      - name: build
        run: ./build-current.sh
